### ISSUE TITLE
New Feature: Big Query integration

### ISSUE THREAD

**Issue by Jujubalandia** [opendatadiscovery/odd-platform#353] opened 2022-01-11 18:24 UTC
Will be nice to have this product integrated with Bigquery, one of the most widely common data warehouse

**Comment by DementevNikita** [comment] 2022-01-12 11:21
Hey @Jujubalandia!
Thank you for the feature request! We will to add this into our roadmap and keep you updated here

**Comment by alexeyzavyalov** [comment] 2022-02-16 19:52
Duplicate of #61

**Comment by DementevNikita** [comment] 2022-10-14 16:06
hey @Jujubalandia, sorry it took so long.
https://github.com/opendatadiscovery/odd-collector-gcp

now we have an integration of BigQuery, please take a look. If you have more questions and bug reports, please feel free to create issues in odd-collector-gcp repository

**Closed by DementevNikita** 2022-10-14 16:06 UTC
