### ISSUE TITLE
Duplicate DataSetField oddrns while ingesting from Hive

### ISSUE THREAD

**Issue by bigdata-spec** [opendatadiscovery/odd-platform#1202] opened 2023-01-03 09:27 UTC
Hi，I meet someting wrong with catalog：
```
collector_config.yaml
platform_host_url: http://192.168.56.118:8089
default_pulling_interval: 3
token: "kb3kd5OgoftyHIOe13vNCndaODo3im5sCN8LtBVi"
plugins:
  - type: hive
    name: hive_adapter_zone_ads
    host: 10.131.122.15
    port: 9083
    database: zone_ads
```
because 8080 is used，so I use 8089 for odd-platform，
I run **docker-compose -f docker/demo.yaml restart odd-collector**
![image](https://user-images.githubusercontent.com/23710717/210330154-4c035ab2-6b4b-4f08-8d12-6a7606067d49.png)

and there is no data in catalog，
![image](https://user-images.githubusercontent.com/23710717/210330392-c2bdbb3f-18d8-4d42-a176-e64bc14424da.png)

**Comment by DementevNikita** [comment] 2023-01-03 09:56
Hey @bigdata-spec!
Thank you for reaching out to us!

Can you send logs from the odd-platform service? It seems like a bug

**Comment by bigdata-spec** [comment] 2023-01-04 05:19
> Hey @bigdata-spec! Thank you for reaching out to us!
> 
> Can you send logs from the odd-platform service? It looks like a bug

@DementevNikita  Thank you very much，when I collector Hive，what port should I use **9083 or 10000**？
my **collector_config.yaml** is right？**database: zone_ads**  it seems not take effect.
more log as：
```
[2022-12-16 23:23:54,095] WARNING in root: Hive adapter can't retrieve statistics for 'vin' in 'demo_20210217_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:54,147] WARNING in root: Hive adapter can't retrieve statistics for 'vin_model_name' in 'demo_20210217_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:54,209] WARNING in root: Hive adapter can't retrieve statistics for 'vin_brand_name' in 'demo_20210217_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:54,255] WARNING in root: Hive adapter can't retrieve statistics for 'create_time' in 'demo_20210217_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:54,307] WARNING in root: Hive adapter can't retrieve statistics for 'update_time' in 'demo_20210217_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:54,359] WARNING in root: Hive adapter can't retrieve statistics for 'dt' in 'demo_20210217_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:54,401] INFO in root: Hive adapter table statistics for 'test_dimension_table' is not available. Stats has not been gathered. 
[2022-12-16 23:23:54,449] INFO in root: Hive adapter table statistics for 'test_flink_vehicle_status_hi' is not available. Stats has not been gathered. 
[2022-12-16 23:23:54,496] INFO in root: Hive adapter table statistics for 'test_sql_env' is not available. Stats has not been gathered. 
[2022-12-16 23:23:55,484] INFO in root: Hive adapter table statistics for 'dim_as28_adas_signal_list_22' is not available. Stats has not been gathered. 
[2022-12-16 23:23:55,530] INFO in root: Hive adapter table statistics for 'dwd_ep33_hpc_camera_signal_pre_hi' is not available. Stats has not been gathered. 
[2022-12-16 23:23:55,586] INFO in root: Hive adapter table statistics for 'dwd_ep33_imate_camera_signal_pre_hi' is not available. Stats has not been gathered. 
[2022-12-16 23:23:55,701] WARNING in root: Hive adapter can't retrieve statistics for 'src_player' in 'follow'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:55,768] WARNING in root: Hive adapter can't retrieve statistics for 'dst_player' in 'follow'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:55,827] WARNING in root: Hive adapter can't retrieve statistics for 'degree' in 'follow'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:55,876] INFO in root: Hive adapter table statistics for 'linkis_hive_ddl' is not available. Stats has not been gathered. 
[2022-12-16 23:23:55,927] INFO in root: Hive adapter table statistics for 'linkis_hive_fql_66' is not available. Stats has not been gathered. 
[2022-12-16 23:23:56,028] WARNING in root: Hive adapter can't retrieve statistics for 'bucket_pk' in 'linkis_mysql_fql'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,085] WARNING in root: Hive adapter can't retrieve statistics for 'name' in 'linkis_mysql_fql'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,143] WARNING in root: Hive adapter can't retrieve statistics for 'item_id' in 'linkis_mysql_fql'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,246] WARNING in root: Hive adapter can't retrieve statistics for 'bucket_pk' in 'linkis_mysql_fql_21'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,544] WARNING in root: Hive adapter can't retrieve statistics for 'name' in 'linkis_mysql_fql_21'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,599] WARNING in root: Hive adapter can't retrieve statistics for 'item_id' in 'linkis_mysql_fql_21'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,706] WARNING in root: Hive adapter can't retrieve statistics for 'message_id' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,763] WARNING in root: Hive adapter can't retrieve statistics for 'event_id' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,818] WARNING in root: Hive adapter can't retrieve statistics for 'vin' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,877] WARNING in root: Hive adapter can't retrieve statistics for 'vehicle_type' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:56,935] WARNING in root: Hive adapter can't retrieve statistics for 'version' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,239] WARNING in root: Hive adapter can't retrieve statistics for 'message_compress_time' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,293] WARNING in root: Hive adapter can't retrieve statistics for 'file_name' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,357] WARNING in root: Hive adapter can't retrieve statistics for 'file_url' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,416] WARNING in root: Hive adapter can't retrieve statistics for 'unique_id' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,471] WARNING in root: Hive adapter can't retrieve statistics for 'file_type' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,527] WARNING in root: Hive adapter can't retrieve statistics for 'source' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,586] WARNING in root: Hive adapter can't retrieve statistics for 'message_receive_time' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,889] WARNING in root: Hive adapter can't retrieve statistics for 'etl_time' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:57,951] WARNING in root: Hive adapter can't retrieve statistics for 'dt' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,015] WARNING in root: Hive adapter can't retrieve statistics for 'hh' in 'ods_ep33_imate_camera_signal_hi'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,122] WARNING in root: Hive adapter can't retrieve statistics for 'playerid' in 'player'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,184] WARNING in root: Hive adapter can't retrieve statistics for 'age' in 'player'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,241] WARNING in root: Hive adapter can't retrieve statistics for 'name' in 'player'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,354] WARNING in root: Hive adapter can't retrieve statistics for 'playerid' in 'serve'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,415] WARNING in root: Hive adapter can't retrieve statistics for 'teamid' in 'serve'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,491] WARNING in root: Hive adapter can't retrieve statistics for 'start_year' in 'serve'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,550] WARNING in root: Hive adapter can't retrieve statistics for 'end_year' in 'serve'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,659] WARNING in root: Hive adapter can't retrieve statistics for 'id' in 't_ppp'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,719] WARNING in root: Hive adapter can't retrieve statistics for 'pice' in 't_ppp'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,775] WARNING in root: Hive adapter can't retrieve statistics for 'createtime' in 't_ppp'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,877] WARNING in root: Hive adapter can't retrieve statistics for 'id' in 't_ppp_bk'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:58,935] WARNING in root: Hive adapter can't retrieve statistics for 'pice' in 't_ppp_bk'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:59,009] WARNING in root: Hive adapter can't retrieve statistics for 'createtime' in 't_ppp_bk'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:59,119] WARNING in root: Hive adapter can't retrieve statistics for 'id' in 't_ppp_cycle'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:59,177] WARNING in root: Hive adapter can't retrieve statistics for 'pice' in 't_ppp_cycle'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:59,232] WARNING in root: Hive adapter can't retrieve statistics for 'createtime' in 't_ppp_cycle'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:59,353] WARNING in root: Hive adapter can't retrieve statistics for 'teamid' in 'team'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:59,402] WARNING in root: Hive adapter can't retrieve statistics for 'name' in 'team'. Generated an exception: get_table_column_statistics failed: unknown result. May be the type: array, struct, map, union
[2022-12-16 23:23:59,450] INFO in root: Hive adapter table statistics for 'test22' is not available. Stats has not been gathered. 
[2022-12-16 23:23:59,451] INFO in root: Hive adapter connection is closed
[2022-12-16 23:23:59,451] INFO in root: Hive adapter loaded 877 DataEntity(s) from database in 383.03684486297425 seconds
[2022-12-16 23:24:00,102] WARNING in apscheduler.scheduler: Execution of job "SyncJob.start (trigger: interval[0:03:00], next run at: 2022-12-16 23:20:36 UTC)" skipped: maximum number of running instances reached (1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/odd_collector_sdk/job.py", line 25, in log_execution
    yield
  File "/usr/local/lib/python3.9/site-packages/odd_collector_sdk/job.py", line 88, in start
    await self.send_metadata(metadata=del_, session=session)
  File "/usr/local/lib/python3.9/site-packages/odd_collector_sdk/job.py", line 45, in send_metadata
    await self._api.ingest_data(metadata, session)
  File "/usr/local/lib/python3.9/site-packages/odd_collector_sdk/api/datasource_api.py", line 48, in ingest_data
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.56.118:8089/ingestion/entities')
[2022-12-16 23:24:00,665] ERROR in odd-collector-sdk: 500, message='Internal Server Error', url=URL('http://192.168.56.118:8089/ingestion/entities')
[2022-12-16 23:24:00,673] INFO in apscheduler.executors.default: Job "SyncJob.start (trigger: interval[0:03:00], next run at: 2022-12-16 23:26:36 UTC)" executed successfully
```

**Comment by DementevNikita** [comment] 2023-01-04 10:45
@bigdata-spec it looks like your collector's config is correct as it loaded 877 datasets. The root cause is in the ODD Platform itself.

`docker-compose -f docker/demo.yaml logs -f odd-platform` command should return logs from the platform itself. Can you send them here?

**Comment by bigdata-spec** [comment] 2023-01-05 01:25
> docker-compose -f docker/demo.yaml logs -f odd-platform

@DementevNikita  Thank you,it seems error log **Duplicate key**
```
odd-platform_1           | java.lang.IllegalStateException: Duplicate key //hive/host/10.135.120.15/databases/zone_dw/tables/dwd_as28_adas_log_event_detail_hi/columns/signals/subcolumns/struct/subcolumns/string (attempted merging values DatasetFieldPojo (null, string, //hive/host/10.135.120.15/databases/zone_dw/tables/dwd_as28_adas_log_event_detail_hi/columns/signals/subcolumns/struct/subcolumns/string, //hive/host/10.135.120.15/databases/zone_dw/tables/dwd_as28_adas_log_event_detail_hi/columns/signals/subcolumns/struct, 0, {"boolean_stats":null,"integer_stats":null,"binary_stats":null,"complex_stats":null,"datetime_stats":null,"tags":null,"number_stats":null,"string_stats":null}, {"is_nullable":true,"logical_type":"string","type":"TYPE_STRING"}, false, false, null, null, false, false) and DatasetFieldPojo (null, string, //hive/host/10.135.120.15/databases/zone_dw/tables/dwd_as28_adas_log_event_detail_hi/columns/signals/subcolumns/struct/subcolumns/string, //hive/host/10.135.120.15/databases/zone_dw/tables/dwd_as28_adas_log_event_detail_hi/columns/signals/subcolumns/struct, 0, {"boolean_stats":null,"integer_stats":null,"binary_stats":null,"complex_stats":null,"datetime_stats":null,"tags":null,"number_stats":null,"string_stats":null}, {"is_nullable":true,"logical_type":"string","type":"TYPE_STRING"}, false, false, null, null, false, false))
odd-platform_1           | 	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[na:na]
odd-platform_1           | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
odd-platform_1           | Error has been observed at the following site(s):
odd-platform_1           | 	*__checkpoint ⇢ Handler org.opendatadiscovery.oddplatform.controller.IngestionController#postDataEntityList(Mono, ServerWebExchange) [DispatcherHandler]
odd-platform_1           | Original Stack Trace:
odd-platform_1           | 		at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
odd-platform_1           | 		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.repository.reactive.ReactiveDatasetFieldRepositoryImpl.getExistingFieldsByOddrnAndType(ReactiveDatasetFieldRepositoryImpl.java:74) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.repository.reactive.ReactiveDatasetFieldRepositoryImpl$$FastClassBySpringCGLIB$$63e0da7e.invoke(<generated>) ~[classes/:na]
odd-platform_1           | 		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.repository.reactive.ReactiveDatasetFieldRepositoryImpl$$EnhancerBySpringCGLIB$$6719f08.getExistingFieldsByOddrnAndType(<generated>) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.DatasetFieldServiceImpl.createOrUpdateDatasetFields(DatasetFieldServiceImpl.java:99) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.DatasetFieldServiceImpl$$FastClassBySpringCGLIB$$f0c6f0d2.invoke(<generated>) ~[classes/:na]
odd-platform_1           | 		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.19.jar:5.3.19]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.DatasetFieldServiceImpl$$EnhancerBySpringCGLIB$$24cdd1b4.createOrUpdateDatasetFields(<generated>) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.DatasetStructureServiceImpl.createDatasetStructure(DatasetStructureServiceImpl.java:39) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.ingestion.processor.DatasetStructureIngestionRequestProcessor.ingestNewDatasetStructure(DatasetStructureIngestionRequestProcessor.java:69) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.ingestion.processor.DatasetStructureIngestionRequestProcessor.process(DatasetStructureIngestionRequestProcessor.java:36) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.ingestion.processor.IngestionProcessorChain.lambda$getPhaseExecutions$5(IngestionProcessorChain.java:53) ~[classes/:na]
odd-platform_1           | 		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
odd-platform_1           | 		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[na:na]
odd-platform_1           | 		at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[na:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.ingestion.processor.IngestionProcessorChain.getPhaseExecutions(IngestionProcessorChain.java:54) ~[classes/:na]
odd-platform_1           | 		at org.opendatadiscovery.oddplatform.service.ingestion.processor.IngestionProcessorChain.lambda$processIngestionRequest$2(IngestionProcessorChain.java:33) ~[classes/:na]
odd-platform_1           | 		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.tryOnNext(FluxHandleFuseable.java:116) ~[reactor-core-3.4.17.jar:3.4.17]
odd-platform_1           | 		at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.slowPath(FluxIterable.java:574) ~[reactor-core-3.4.17.jar:3.4.17]
odd-platform_1           | 		at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:532) ~[reactor-core-3.4.17.jar:3.4.17]
odd-platform_1           | 		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:257) ~[reactor-core-3.4.17.jar:3.4.17]
odd-platform_1           | 		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:236) ~[reactor-core-3.4.17.jar:3.4.17]ERROR: Aborting.
```

**Comment by DementevNikita** [comment] 2023-01-05 09:13
gotcha, thank you @bigdata-spec!

We'll take a look and get back to you when it's fixed

**Comment by DementevNikita** [comment] 2023-01-27 10:47
On the second look, it does look like a ODDRN construction problem when there are dataset fields with complex structure like maps, list, structs, etc.

@Vixtir could you please take a look at the ODDRN generator and try recreating the problem?

**Comment by Vixtir** [comment] 2023-01-30 08:47
Hi @bigdata-spec , I have created new odd-collector release, with fixed duplicates.
Could you please pull [latest odd-collector image](https://github.com/opendatadiscovery/odd-collector/pkgs/container/odd-collector) and try again.

**Comment by DementevNikita** [comment] 2023-01-31 07:55
Closing this due to releasing a new version of the collector which should fix the problem.

@bigdata-spec please feel free to reopen, if the issue still remains.

Thank you for reporting this, we appreciate your contribution!

**Closed by DementevNikita** 2023-01-31 07:55 UTC
Labels: kind: bug, func: Ingestion API
