### ISSUE TITLE
Status of puller condition.

### ISSUE THREAD

**Issue by Leshe4ka** [opendatadiscovery/odd-platform#389] opened 2022-01-22 16:56 UTC
### Is your proposal related to a problem?

Sometimes i don't understand whether the puller works or not?

### Describe the solution you'd like

Add puller work status and time of the latest pull.

### Additional context

[Figma styles](https://www.figma.com/file/yiL1CRyHsOEeY45NesWdiC/ODD?node-id=955%3A27146)

**Comment by DementevNikita** [comment] 2022-01-22 16:58
duplicate of https://github.com/opendatadiscovery/odd-platform/issues/355

**Closed by DementevNikita** 2022-01-22 16:58 UTC
Labels: status: duplicate, scope: backend, scope: frontend, kind: feature
