### ISSUE TITLE
Problem when trying to install odd on linux server

### ISSUE THREAD

**Issue by fireragnarous** [opendatadiscovery/odd-platform#746] opened 2022-06-15 09:23 UTC
**Describe the bug**
I have succeeded in using odd platform on my personal windows PC according to your instruction and now I want to use it on my linux server. However the port 8080 has been occupied on my server, I changed the demo.yaml in following way and caused error report.

 ![1](https://user-images.githubusercontent.com/55270059/173790494-649b34b3-9f70-4063-9b18-02ee5b25cae6.JPG)

**Set up**
CentOS Linux release 7.9.2009
Linux version 4.19.134
Docker version 20.10.10
docker-compose version 1.29.2

**Steps to Reproduce**
Just same as the procedure on your tutorial except changing the port of odd-platform.
> https://github.com/opendatadiscovery/odd-platform/blob/main/docker/README.md

**Screenshots**
Here are the detailed error report.
![2](https://user-images.githubusercontent.com/55270059/173792582-fb6d0351-32cb-44c2-a9c8-69ae04586395.JPG)

![3](https://user-images.githubusercontent.com/55270059/173792595-b980a4f1-a2df-46e4-bb3d-3d930b25837b.JPG)

![4](https://user-images.githubusercontent.com/55270059/173792601-b58ccb3f-13f3-46e2-87d5-0a56ae47a274.JPG)

![5](https://user-images.githubusercontent.com/55270059/173792611-b511ef44-c8f9-4d22-afbf-23b3c67eaf42.JPG)

I wonder if the way I changed the port was not correct and I look forward to your precious advice.

**Comment by DementevNikita** [comment] 2022-06-15 09:28
Hey there @fireragnarous!
Thank you for letting us know, we will take a look ASAP

**Comment by DementevNikita** [comment] 2022-06-15 09:37
@fireragnarous also, can you try to kill all of the docker containers with `docker-compose -f docker/demo.yaml down --volume --remove-orphans` and try completing Step 1 again. This error might occur when you're trying to start the application again without dropping the database.

From our side we are going to enhance the injector in a way that it won't try to create data sources when they are already created.

**Comment by fireragnarous** [comment] 2022-06-15 10:10
> @fireragnarous also, can you try to kill all of the docker containers with `docker-compose -f docker/demo.yaml down --volume --remove-orphans` and try completing Step 1 again? This error might occur when you're trying to restart the application without dropping the database.
> 
> From our side we are going to enhance the injector in a way that it won't try to create data sources when they are already created.

Thanks for your advice, I have tried the two steps above but it seems not work, the error report is still the same.
By the way, is there any more detailed document which can introduce function of  the platform, I'd like to try it on windows first.

**Comment by DementevNikita** [comment] 2022-06-15 11:35
> > @fireragnarous also, can you try to kill all of the docker containers with `docker-compose -f docker/demo.yaml down --volume --remove-orphans` and try completing Step 1 again? This error might occur when you're trying to restart the application without dropping the database.
> > From our side we are going to enhance the injector in a way that it won't try to create data sources when they are already created.
> 
> Thanks for your advice, I have tried the two steps above but it seems not work, the error report is still the same. By the way, is there any more detailed document which can introduce function of the platform, I'd like to try it on windows first.

I'll take a look at the demo today, gonna run it on Centos machine just to make sure we didn't miss anything and get back to you.

As for the functionality:
1. [This](https://github.com/opendatadiscovery/opendatadiscovery-specification/blob/main/specification/specification.md) document describes what, why and how we intend to solve Data DIscovery issues.
2. [Here](https://docs.opendatadiscovery.org/features) is the list of ODD Platform's features 
3. And [this](https://docs.opendatadiscovery.org/use_cases) is a list of use cases

If there are more questions from your side after reading these documents, please feel free to ask. You can reach us:
1. By creating an issue here
2. By joining our [Slack community](https://go.opendatadiscovery.org/slack)
3. By scheduling a call with us via [our website](https://opendatadiscovery.org/)

**Comment by DementevNikita** [comment] 2022-06-15 12:19
@fireragnarous I've just tried to reproduce on Linux machine, everything works as expected.

Please make sure that after running `docker-compose -f docker/demo.yaml down --volume --remove-orphans` there are no ODD related containers in running state and there are no ODD related volumes. In the screen attached I can see log statements "Recreating ..." which means that there was docker containers running before you've ran `docker-compose -f docker/demo.yaml up -d odd-platform-enricher`. Also even if this error occurs it means that there's an ingested metadata in ODD Platform already, it just cannot inject it again. I'd be extremely appreciated if you could double-check that.

As for the enricher, we cannot make an "idempotent" enricher at this point. In step 1 it creates data sources and retrieves tokens to send ingestion requests. We can't retrieve those tokens via API after the data source is created due to security reasons.

I'm going to close this issue, but feel free reopen it if you believe I am wrong.

**Closed by DementevNikita** 2022-06-15 12:19 UTC
Labels: kind: bug, scope: demo, status: to reproduce
