### ISSUE TITLE
Add content placeholders for loading page content.

### ISSUE THREAD

**Issue by soffest** [opendatadiscovery/odd-platform#55] opened 2021-07-28 11:53 UTC
- [ ] Data Entity Details: Overview
- [ ] Data Entity Details: Structure
- [ ] Data Entity Details: Lineage
- [ ] Data Entity Details: Test Reports
- [ ] Search Results
- [ ] Search Filters
- [ ] Home Page

**Comment by DementevNikita** [comment] 2021-08-02 10:51
Duplicate of https://github.com/opendatadiscovery/odd-platform/issues/32

**Closed by DementevNikita** 2021-08-02 10:51 UTC
Labels: enhancement, frontend
